// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPs5Z5rjkbSFn6iTVUEi1fEQ0i_mHAoY0',
    appId: '1:200261688395:web:902b1fb89e379b2c0581ce',
    messagingSenderId: '200261688395',
    projectId: 'spotifake-2382c',
    authDomain: 'spotifake-2382c.firebaseapp.com',
    storageBucket: 'spotifake-2382c.firebasestorage.app',
    measurementId: 'G-N9FZ34JD2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg2P1yGYA_ZWn8XAQnkNLbknZ3dzQSdMg',
    appId: '1:200261688395:android:b2aa0a9bdd63c8ea0581ce',
    messagingSenderId: '200261688395',
    projectId: 'spotifake-2382c',
    storageBucket: 'spotifake-2382c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Uq0vUcEeTIZ66jUykpL_PsdhbO8Hx-A',
    appId: '1:200261688395:ios:3f1f2effbae46af50581ce',
    messagingSenderId: '200261688395',
    projectId: 'spotifake-2382c',
    storageBucket: 'spotifake-2382c.firebasestorage.app',
    iosBundleId: 'com.example.spotifake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Uq0vUcEeTIZ66jUykpL_PsdhbO8Hx-A',
    appId: '1:200261688395:ios:3f1f2effbae46af50581ce',
    messagingSenderId: '200261688395',
    projectId: 'spotifake-2382c',
    storageBucket: 'spotifake-2382c.firebasestorage.app',
    iosBundleId: 'com.example.spotifake',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPs5Z5rjkbSFn6iTVUEi1fEQ0i_mHAoY0',
    appId: '1:200261688395:web:51919805d968deee0581ce',
    messagingSenderId: '200261688395',
    projectId: 'spotifake-2382c',
    authDomain: 'spotifake-2382c.firebaseapp.com',
    storageBucket: 'spotifake-2382c.firebasestorage.app',
    measurementId: 'G-4NBM6GB11L',
  );
}
